export const productItems=[
         {
             "id":"1",
             "name":"samosa",
             "price":"10",
             "about":"about",
             "avatar":"s",
             "image":"./Images/samosa.jpg"
         },
         {
            "id":"2",
            "name":"burger",
            "price":"40",
            "about":"about",
            "avatar":"b",
            "image":"./Images/burger.jpg"
        },
        {
            "id":"3",
            "name":"fries",
            "price":"20",
            "about":"about",
            "avatar":"f",
            "image":"./Images/fries.jpg"
        },
        {
            "id":"4",
            "name":"hotdog",
            "price":"10",
            "about":"about",
            "avatar":"h",
            "image":"./Images/hotdog.jpg"
        },
        {
            "id":"5",
            "name":"patty",
            "price":"10",
            "about":"about",
            "avatar":"p",
            "image":"./Images/patty.jpg"
        },
        {
            "id":"6",
            "name":"tea",
            "price":"10",
            "about":"about",
            "avatar":"t",
            "image":"./Images/tea.jpg"
        }

    ]
